export const mediaLibrary = [
  {
    id: 'vid-1',
    type: 'video',
    title: 'Salutation discrète',
    tags: ['R_C_E_3_1', 'R_C_E_3_2'],
    annotations: [
      { time: 0.8, label: 'R_C_E_3_1' },
      { time: 2.4, label: 'R_C_E_3_2' },
      { time: 4.1, label: 'R_C_E_4_0' },
    ],
    src: 'flower.mp4', // Fichier dans /ressources/
    description: 'Inclinaison de la tête marquant un salut poli et mesuré.',
    fps: 30,
  },
  {
    id: 'vid-2',
    type: 'video',
    title: 'Agitation défensive',
    tags: ['R_D_B_1_0', 'R_D_B_2_3'],
    annotations: [
      { time: 0.5, label: 'R_D_B_1_0' },
      { time: 1.9, label: 'R_D_B_2_3' },
      { time: 3.2, label: 'R_D_B_2_4' },
    ],
    src: 'flower.mp4',
    description: 'Bras croisés accompagnés d\'un recul du buste, signal d\'auto-protection.',
    fps: 30,
  },
  {
    id: 'vid-3',
    type: 'video',
    title: 'Sourire contenu',
    tags: ['R_V_S_1_0', 'R_V_S_1_2'],
    annotations: [
      { time: 0.6, label: 'R_V_S_1_0' },
      { time: 1.8, label: 'R_V_S_1_2' },
      { time: 3.5, label: 'R_V_S_1_1' },
    ],
    src: 'flower.mp4',
    description: 'Sourire discret qui s\'élargit légèrement sans dévoiler les dents.',
    fps: 30,
  },
  {
    id: 'vid-4',
    type: 'video',
    title: 'Regard appuyé',
    tags: ['R_R_A_2_0', 'R_R_A_2_1'],
    annotations: [
      { time: 1.2, label: 'R_R_A_2_0' },
      { time: 2.7, label: 'R_R_A_2_1' },
      { time: 4.3, label: 'R_R_A_2_2' },
    ],
    src: 'flower.mp4',
    description: 'Maintien d\'un contact visuel prolongé, signe de détermination.',
    fps: 30,
  },
  {
    id: 'vid-5',
    type: 'video',
    title: 'Inclinaison interrogative',
    tags: ['R_C_Q_0_1', 'R_C_Q_0_2'],
    annotations: [
      { time: 0.4, label: 'R_C_Q_0_1' },
      { time: 2.1, label: 'R_C_Q_0_2' },
      { time: 3.9, label: 'R_C_Q_0_3' },
    ],
    src: 'flower.mp4',
    description: 'Tête penchée sur le côté traduisant la curiosité.',
    fps: 30,
  },
  {
    id: 'vid-6',
    type: 'video',
    title: 'Main ouverte apaisante',
    tags: ['R_M_O_1_0', 'R_M_O_1_1'],
    annotations: [
      { time: 1.1, label: 'R_M_O_1_0' },
      { time: 2.6, label: 'R_M_O_1_1' },
      { time: 4.4, label: 'R_M_O_1_2' },
    ],
    src: 'flower.mp4',
    description: 'Paume visible et tournée vers l\'interlocuteur pour apaiser.',
    fps: 30,
  },
  {
    id: 'vid-7',
    type: 'video',
    title: 'Pas mesuré',
    tags: ['R_P_M_0_1', 'R_P_M_0_2'],
    annotations: [
      { time: 0.9, label: 'R_P_M_0_1' },
      { time: 2.2, label: 'R_P_M_0_2' },
      { time: 3.8, label: 'R_P_M_0_3' },
    ],
    src: 'flower.mp4',
    description: 'Déplacement lent et contrôlé indiquant la prudence.',
    fps: 30,
  },
  {
    id: 'vid-8',
    type: 'video',
    title: 'Dos droit affirmé',
    tags: ['R_P_S_2_0', 'R_P_S_2_1'],
    annotations: [
      { time: 0.7, label: 'R_P_S_2_0' },
      { time: 2.0, label: 'R_P_S_2_1' },
      { time: 3.6, label: 'R_P_S_2_2' },
    ],
    src: 'flower.mp4',
    description: 'Posture verticale signifiant l\'assurance.',
    fps: 30,
  },
  {
    id: 'vid-9',
    type: 'video',
    title: 'Geste de la main invitant',
    tags: ['R_M_I_1_0', 'R_M_I_1_1'],
    annotations: [
      { time: 1.0, label: 'R_M_I_1_0' },
      { time: 2.5, label: 'R_M_I_1_1' },
      { time: 4.0, label: 'R_M_I_1_2' },
    ],
    src: 'flower.mp4',
    description: 'Mouvement ample du bras pour encourager à avancer.',
    fps: 30,
  },
  {
    id: 'vid-10',
    type: 'video',
    title: 'Pincement de lèvres',
    tags: ['R_V_L_0_1', 'R_V_L_0_2'],
    annotations: [
      { time: 0.3, label: 'R_V_L_0_1' },
      { time: 1.6, label: 'R_V_L_0_2' },
      { time: 3.1, label: 'R_V_L_0_3' },
    ],
    src: 'flower.mp4',
    description: 'Lèvres serrées brièvement pour retenir une réaction.',
    fps: 30,
  },
  {
    id: 'vid-11',
    type: 'video',
    title: 'Grattement nerveux',
    tags: ['R_M_N_2_0', 'R_M_N_2_1'],
    annotations: [
      { time: 0.8, label: 'R_M_N_2_0' },
      { time: 2.3, label: 'R_M_N_2_1' },
      { time: 3.7, label: 'R_M_N_2_2' },
    ],
    src: 'flower.mp4',
    description: 'Grattement du poignet révélant une tension.',
    fps: 30,
  },
  {
    id: 'vid-12',
    type: 'video',
    title: 'Redressement soudain',
    tags: ['R_P_R_3_0', 'R_P_R_3_1'],
    annotations: [
      { time: 0.5, label: 'R_P_R_3_0' },
      { time: 1.9, label: 'R_P_R_3_1' },
      { time: 3.4, label: 'R_P_R_3_2' },
    ],
    src: 'flower.mp4',
    description: 'Ajustement brusque de la posture pour se donner contenance.',
    fps: 30,
  },
  {
    id: 'vid-13',
    type: 'video',
    title: 'Mouvement d\'épaules',
    tags: ['R_E_S_0_1', 'R_E_S_0_2'],
    annotations: [
      { time: 0.9, label: 'R_E_S_0_1' },
      { time: 2.4, label: 'R_E_S_0_2' },
      { time: 4.2, label: 'R_E_S_0_3' },
    ],
    src: 'flower.mp4',
    description: 'Haussement léger pour signifier l\'incertitude.',
    fps: 30,
  },
  {
    id: 'vid-14',
    type: 'video',
    title: 'Clignement accéléré',
    tags: ['R_R_B_1_0', 'R_R_B_1_1'],
    annotations: [
      { time: 0.6, label: 'R_R_B_1_0' },
      { time: 1.5, label: 'R_R_B_1_1' },
      { time: 2.9, label: 'R_R_B_1_2' },
    ],
    src: 'flower.mp4',
    description: 'Série de clignements courts traduisant une gêne.',
    fps: 30,
  },
  {
    id: 'vid-15',
    type: 'video',
    title: 'Bras ouverts',
    tags: ['R_M_A_0_1', 'R_M_A_0_2'],
    annotations: [
      { time: 0.7, label: 'R_M_A_0_1' },
      { time: 2.0, label: 'R_M_A_0_2' },
      { time: 3.3, label: 'R_M_A_0_3' },
    ],
    src: 'flower.mp4',
    description: 'Ouverture des bras pour manifester la disponibilité.',
    fps: 30,
  },
  {
    id: 'vid-16',
    type: 'video',
    title: 'Tête baissée',
    tags: ['R_C_B_0_1', 'R_C_B_0_2'],
    annotations: [
      { time: 0.4, label: 'R_C_B_0_1' },
      { time: 1.7, label: 'R_C_B_0_2' },
      { time: 3.0, label: 'R_C_B_0_3' },
    ],
    src: 'flower.mp4',
    description: 'Abaissement du menton indiquant la réserve.',
    fps: 30,
  },
  {
    id: 'vid-17',
    type: 'video',
    title: 'Pas en retrait',
    tags: ['R_P_R_1_0', 'R_P_R_1_1'],
    annotations: [
      { time: 0.5, label: 'R_P_R_1_0' },
      { time: 1.8, label: 'R_P_R_1_1' },
      { time: 3.2, label: 'R_P_R_1_2' },
    ],
    src: 'flower.mp4',
    description: 'Recul du pied traduisant un doute.',
    fps: 30,
  },
  {
    id: 'vid-18',
    type: 'video',
    title: 'Mains jointes',
    tags: ['R_M_J_0_1', 'R_M_J_0_2'],
    annotations: [
      { time: 1.0, label: 'R_M_J_0_1' },
      { time: 2.8, label: 'R_M_J_0_2' },
      { time: 4.2, label: 'R_M_J_0_3' },
    ],
    src: 'flower.mp4',
    description: 'Doigts entremêlés pour maîtriser une émotion.',
    fps: 30,
  },
  {
    id: 'photo-1',
    type: 'photo',
    title: 'Main sur le cœur',
    tags: ['R_H_C_1_0', 'R_H_C_1_1'],
    src: 'photo-1.jpg',
    description: 'Geste associé à l\'assurance de bonne foi.',
  },
  {
    id: 'photo-2',
    type: 'photo',
    title: 'Regard fuyant',
    tags: ['R_R_F_0_1', 'R_R_F_0_2'],
    src: 'photo-2.jpg',
    description: 'Les yeux évitent le contact, marque d\'inconfort.',
  },
  {
    id: 'photo-3',
    type: 'photo',
    title: 'Sourcil relevé',
    tags: ['R_V_S_2_0', 'R_V_S_2_1'],
    src: 'photo-3.jpg',
    description: 'Surprise marquée par un sourcil arquant légèrement.',
  },
  {
    id: 'photo-4',
    type: 'photo',
    title: 'Épaule tournée',
    tags: ['R_P_D_1_0', 'R_P_D_1_2'],
    src: 'photo-4.jpg',
    description: 'Posture orientée vers l\'extérieur traduisant un désengagement.',
  },
  {
    id: 'photo-5',
    type: 'photo',
    title: 'Poing fermé',
    tags: ['R_M_F_0_1', 'R_M_F_0_2'],
    src: 'photo-5.jpg',
    description: 'Main serrée symbolisant une retenue émotionnelle.',
  },
  {
    id: 'photo-6',
    type: 'photo',
    title: 'Regard direct',
    tags: ['R_R_D_1_0', 'R_R_D_1_1'],
    src: 'photo-6.jpg',
    description: 'Face à face affirmé marquant la franchise.',
  },
  {
    id: 'photo-7',
    type: 'photo',
    title: 'Bras croisés serrés',
    tags: ['R_M_C_2_1', 'R_M_C_2_3'],
    src: 'photo-7.jpg',
    description: 'Croisement ferme signalant la fermeture.',
  },
  {
    id: 'photo-8',
    type: 'photo',
    title: 'Mains en prière',
    tags: ['R_M_P_1_0', 'R_M_P_1_1'],
    src: 'photo-8.jpg',
    description: 'Geste de conciliation et de demande.',
  },
  {
    id: 'photo-9',
    type: 'photo',
    title: 'Regard latéral',
    tags: ['R_R_L_0_1', 'R_R_L_0_2'],
    src: 'photo-9.jpg',
    description: 'Observation discrète depuis la périphérie.',
  },
  {
    id: 'photo-10',
    type: 'photo',
    title: 'Mâchoire serrée',
    tags: ['R_V_M_1_0', 'R_V_M_1_1'],
    src: 'photo-10.jpg',
    description: 'Tension faciale visible au niveau de la mâchoire.',
  },
  {
    id: 'photo-11',
    type: 'photo',
    title: 'Buste incliné',
    tags: ['R_P_I_0_1', 'R_P_I_0_2'],
    src: 'photo-11.jpg',
    description: 'Inclinaison vers l\'avant signe d\'intérêt.',
  },
  {
    id: 'photo-12',
    type: 'photo',
    title: 'Pieds parallèles',
    tags: ['R_P_S_1_0', 'R_P_S_1_1'],
    src: 'photo-12.jpg',
    description: 'Ancrage stable reflétant l\'équilibre.',
  },
  {
    id: 'photo-13',
    type: 'photo',
    title: 'Menton relevé',
    tags: ['R_C_H_0_1', 'R_C_H_0_2'],
    src: 'photo-13.jpg',
    description: 'Affirmation de soi par un menton haut.',
  },
  {
    id: 'photo-14',
    type: 'photo',
    title: 'Sourire large',
    tags: ['R_V_S_3_0', 'R_V_S_3_1'],
    src: 'photo-14.jpg',
    description: 'Joie manifeste avec sourire éclatant.',
  },
  {
    id: 'photo-15',
    type: 'photo',
    title: 'Regard vers le bas',
    tags: ['R_R_B_0_1', 'R_R_B_0_2'],
    src: 'photo-15.jpg',
    description: 'Humilité ou gêne marquée par les yeux baissés.',
  },
  {
    id: 'photo-16',
    type: 'photo',
    title: 'Paume tournée',
    tags: ['R_M_O_0_1', 'R_M_O_0_2'],
    src: 'photo-16.jpg',
    description: 'Paume visible qui invite à la confiance.',
  },
  {
    id: 'photo-17',
    type: 'photo',
    title: 'Épaule détendue',
    tags: ['R_P_R_0_1', 'R_P_R_0_2'],
    src: 'photo-17.jpg',
    description: 'Relaxation corporelle perceptible dans les épaules.',
  },
];
